version: '3.8'
services:
  db:
    image: loraine/db:latest
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
  client:
    image: loraine/frontend:latest
    build:
      context: front-etg
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
  api:
    image: loraine/backend:latest
    build:
      context: back-etg
      dockerfile: Dockerfile
    ports:
      - '8090:8090'
  nginx:
    image: 'loraine/nginx:latest'
    build:
      context: front-etg/nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
