version: '3.8'
services:
  db:
    image: loraine/db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
  client:
    image: loraine/frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
  api:
    image: loraine/backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - '8090:8090'
